### ISSUE TITLE
Need apolloState support

### ISSUE THREAD

**Issue by monotrue** [l5x/vue-cloudflare-workers#2]
Hi.
I check this template with vue-apollo/ssr.
But in html I got
`"apolloState":{"defaultClient":{}}`

Any minds?

**Comment by sinisterstumble** [comment]
Hello, GraphQL is out of scope of this project. I suggest taking a look at the Vue Apollo [SSR guide](https://vue-apollo.netlify.com/guide/ssr.html#server-entry).

If you have a repository that I can look at DM mcnmr on twitter.
