### ISSUE TITLE
upgrading vue-cli to 4.2.2 ( even 4.1.x ) breaks the app

### ISSUE THREAD

**Issue by valentinvieriu** [l5x/vue-cloudflare-workers#3]
I've found out the hard way ( i've used yarn instead of npm ) that upgrading vue-cli to 4.2.2 breaks the app. It seem that the entry-worker.js gets compiled by some new babel settings, and it remove the async await coding style. This somehow breaks the app when you deploy it to Cloudflare.

**Comment by sinisterstumble** [comment]
#4
