### ISSUE TITLE
Do you plan to maintain this?

### ISSUE THREAD

**Issue by valentinvieriu** [l5x/vue-cloudflare-workers#4]
I've started using your template on couple of my website. I like working with Vue and also Cloudflare workers bring an interesting advantage for ssr.
I really appreciate sharing the code and solving the SSR problem for VUE applications.
I would like to ask if you plan on extending this further or it was just a one time demo / solution.

I'm already extending your my fork and want to know if I should start contributing back with pull requests

**Comment by sinisterstumble** [comment]
Hello,

I'm waiting for Vue 3. Probably the best way to go is to push the necessary changes to the Vue 2 master. We can look into it together.

**Comment by valentinvieriu** [comment]
Perfect! Vue 3 will change the SSR approach. Makes sense!
