### ISSUE TITLE
Vue3 support

### ISSUE THREAD

**Issue by valentinvieriu** [l5x/vue-cloudflare-workers#5]
I loved this setup, and I'm using it for some small projects. 
Now that Vue3 is out, do you plan on supporting Vue3 too? The SSR should be considerably faster than Vue2

**Comment by valentinvieriu** [comment]
By the way, it seems there is something like that for React [Flareact](https://flareact.com/). 
How about a project named vueflare?

**Comment by sinisterstumble** [comment]
@valentinvieriu planning to look into it
